### ISSUE TITLE
Request for Firefox Extension

### ISSUE THREAD

**Issue by sh4hids** [fushatech/tahir#1]
Jazak Allah Khairan for such a nice extension. Please create the same extension for Firefox browser too.

**Comment by ammaristotle** [comment]
Wa iyyakum. It shouldn't be too hard to port this to Firefox (see [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension) for more details).

We'd be happy to take contributions from the community in the form of a pull request to add Firefox (or other browser support).

**Comment by sh4hids** [comment]
@ammaristotle you have to create a new branch for firefox extension. After that I can change the base branch for PR to that branch.

**Comment by fushatech** [comment]
@sh4hids As salamu alaykum brother, JAK for your work! I updated master with a /chrome folder. Can you update your pull request based on the latest commit & put the firefox code into a /firefox folder?

**Comment by fushatech** [comment]
@sh4hids Ta barak Allah, excellent work. Just reviewed the code, tested it, and merged it with master. Will publish to firefox add-ons soon isA.

**Comment by sh4hids** [comment]
Barak Allah Fikum. Closing the issue.
