### ISSUE TITLE
Request to adopt dhikr-extension

### ISSUE THREAD

**Issue by Wulf** [fushatech/tahir#18]
JazakAllah khair for the wonderful extension! Just wondering whether you're willing to adopt [this extension](https://github.com/Wulf/dhikr-extension) under your account. It was an idea by one of my roommates who suggested having a popup appear every X minutes with something beneficial could be a tool by which:

- can remind you to not waste time (sometimes we go on social media to do X, but we end up doing ABCDEF+)
- can remind you to get up and pray
- teach you Arabic words and their translations over time

Currently, it only has 3 words configured to appear, but we can add more:

https://github.com/Wulf/dhikr-extension/blob/master/chrome/background.js#L6-L15

```javascript
const notifications = [{
    title: 'Subḥān Allāh — سبحان الله‎‎',
    message: "God is Perfect.",
}, {
    title: 'Alḥamdulillāh — الحَمْد لله‎‎',
    message: "Praise and thanks belong to God."
}, {
    title: 'Allāhu akbar — الله أكبر',
    message: "God is Greatest."
}]
```

I published this a few years ago, but it got taken down from the AMO because I didn't upload images for the extension or something. Also, I didn't have a chrome developer account so it never made it to the chrome web store.

**Comment by fushatech** [comment]
Wa iyyakum brother! This extension sounds like a great idea, can you send us an email at dev@fushatech.com so we can talk more in sha Allah. Perhaps we can offer it standalone as well as merge it with Asr (https://chrome.google.com/webstore/detail/asr/ncjacmkjnpkjbemlgaoekklcmheopmdi?hl=en-US).

**Comment by Wulf** [comment]
Will do :)
