### ISSUE TITLE
Feature Request: Ability to reveal individual image.

### ISSUE THREAD

**Issue by halfo** [fushatech/tahir#5]
The inspiration of this feature request was taken from Facebook. Facebook masks images that it feels inappropriate in some way. But lets us unmask/reveal that image if we are still interested to see it. It would be a great addition to this extension.

**Comment by sh4hids** [comment]
I thing the feature you are looking for does already exist. If you want to reveal a single image put your mouse pointer on that image and click `Alt+k`, or if you want to reveal all at once click `Alt+l`.

**Comment by halfo** [comment]
My bad! Didn't notice that. Thanks for the great work!
