### ISSUE TITLE
Feature Request: Alt-K should reblur

### ISSUE THREAD

**Issue by fushatech** [fushatech/tahir#6]
Several users have requested the ability to reblur an image after selectively unblurring it. Alt-K should be redesigned to allow the user to both unblur & reblur a selective image. I have finished this feature, and am cleaning up documentation & testing it now before releasing iA.

**Comment by sh4hids** [comment]
Masha Allah. This feature will make the extension more complete.

**Comment by fushatech** [comment]
Featured added for chrome, merged into master. #7
